KUSYS-Demo/KUSYS-Demo/Controllers/StudentCourseController.cs
using KUSYS_Demo.DataModel;
using KUSYS_Demo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KUSYS_Demo.Controllers
{
    public class StudentCourseController : Controller
    {
        private readonly DataContext _context;

        public StudentCourseController(DataContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = new StudentCourseModel();
            model.Courses = _context
                .Courses
                .Include(i => i.studentCourses)
                .ThenInclude(i => i.Student)
                .ToList();

            model.Students = _context
                .Students
                .Include(i => i.studentCourses)
                .ThenInclude(i => i.Course)
                .ToList();

            return View(model);
        }

        [HttpGet]
        public IActionResult EditStudent(int id)
        {
            var student = _context.Students.Find(id);
            ViewBag.Courses = _context.Courses.Include(p => p.studentCourses);

            return View("StudentEditor", student);
        }

        [HttpPost]
        public IActionResult EditStudent(int id, int[] courseid)
        {
            Student student = _context
                .Students
                .Include(s => s.studentCourses)
                .First(i => i.StudentId == id);

            if (student != null)
            {
                student.studentCourses = courseid.Select(cid => new StudentCourse()
                {
                    CourseId = cid,
                    StudentId = id
                }).ToList();

                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

KUSYS-Demo/KUSYS-Demo/Controllers/UserController.cs
using KUSYS_Demo.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace KUSYS_Demo.Controllers
{
    public class UserController : Controller
    {
        private readonly DataContext _context;

        //readonly UserManager<Users> _userManager;
        //readonly SignInManager<Users> _signInManager;
        //public UserController(UserManager<Users> userManager, SignInManager<Users> signInManager)
        //{
        //    _userManager = userManager;
        //    _signInManager = signInManager;
        //}

        public UserController(DataContext context)
        {
            _context = context;
        }
        public IActionResult login()
        {
            Users users = new Users();
            return View(users);
        }


        [HttpPost]
        public async Task<ActionResult> login(Users model)
        {
            Users user = _context.Users.FirstOrDefault(i => i.Username == model.Username && i.Password == model.Password);

            bool kuladi = user.Username.Equals(model.Username, StringComparison.Ordinal);
            bool sfr = user.Password.Equals(model.Password, StringComparison.Ordinal);


            if (user != null && kuladi == true && sfr == true)
            {
                //var claims = new List<Claim>()
                //{
                //        new Claim(ClaimTypes.Name,model.Username)
                //};

                var claims = new List<Claim>() {
                    new Claim(ClaimTypes.NameIdentifier,Convert.ToString(user.id)),
                    //new Claim(ClaimTypes.Name,user.Username),
                    new Claim(ClaimTypes.Role,user.Role)
                    };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    //AllowRefresh = <bool>,
                    // Refreshing the authentication session should be allowed.

                    //ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
                    // The time at which the authentication ticket expires. A 
                    // value set here overrides the ExpireTimeSpan option of 
                    // CookieAuthenticationOptions set with AddCookie.

                    //IsPersistent = true,
                    // Whether the authentication session is persisted across 
                    // multiple requests. When used with cookies, controls
                    // whether the cookie's lifetime is absolute (matching the
                    // lifetime of the authentication ticket) or session-based.

                    //IssuedUtc = <DateTimeOffset>,
                    // The time at which the authentication ticket was issued.

                    //RedirectUri = <string>
                    // The full path or absolute URI to be used as an http 
                    // redirect response value.
                };

                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity),
                    authProperties);

                return RedirectToAction("Index", "Students");

            }
            else
            {
                ModelState.AddModelError("", "Kullanıcı adı veya şifre yanlış");
            }

            return View(model);
        }



        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

KUSYS-Demo/KUSYS-Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KUSYS_Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KUSYS_Demo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KUSYS_Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentCourse" asp-action="Index">Student Course</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - KUSYS_Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>